### ISSUE TITLE
Пользователь библиотеки

### ISSUE THREAD

**Issue by milkina** [coolrich/Lessons#11]
Я так понимаю еще в процессе?
Отформатируйте

**Comment by coolrich** [comment]
Я не совсем понимаю для чего нужен метод returnBook(int count), можно реализовать его как захочется , на пример он может возвращать книги которые были взятые первыми?

**Comment by milkina** [comment]
Реализация в простейшем случае может быть такая:
System.out.println(fullname + "вернул" + count + "книг")

А там придумывайте сами.

**Comment by coolrich** [comment]
Ок. Вроде дописал прогу, все методы реализовал, можете проверять)

**Comment by milkina** [comment]
1.
```
  for (User u :
                    users)
```
Пишите в одну строку:
`  for (User u : users)`

**Comment by coolrich** [comment]
Есть
