### ISSUE TITLE
Car

### ISSUE THREAD

**Issue by milkina** [coolrich/Lessons#13]
1. Неотформатировано
2. Создайте объекты класса Lorry и Sportcar что ли. Вы ж должны ка-то проверить их работоспособность.
3. И вызовите методы move, talk
4. Много лишних пустых строк. Если непонятно где - напомните на уроке посмотрим.

**Comment by coolrich** [comment]
Сделал

**Comment by milkina** [comment]
1. Опять неотформатировано
2. Ой, перепутала c другим дз. Имела ввиду вызвать методы start, stop,turnRight,turnLeft
3. И добавьте геттеры, сеттеры.

**Comment by coolrich** [comment]
Есть

**Comment by milkina** [comment]
Опять неотформатировано

**Comment by coolrich** [comment]
Есть
