### ISSUE TITLE
Flowers

### ISSUE THREAD

**Issue by milkina** [coolrich/Lessons#14]
Еще не доделали?

**Comment by coolrich** [comment]
Сделал

**Comment by coolrich** [comment]
Отформатировал

**Comment by milkina** [comment]
1.  public void printPriceOfFlowers() {
        System.out.println();
    } - что- нибудь  выведите на консоль .
2. for each пишите одной строкой

**Comment by coolrich** [comment]
Есть

**Comment by milkina** [comment]
Flower -for each исправьте еще в одном месте

**Comment by coolrich** [comment]
Есть
