### ISSUE TITLE
Интсрументы

### ISSUE THREAD

**Issue by milkina** [coolrich/Lessons#18]
1.    Вместо 
private Size size = Size.valueOf("SMALL");
 можно 
private Size size = Size.SMALL;

2.  В конструктор тоже можно сразу передавать перечисление:
new Drum(Drum.Size.MEDIUM).  Это как хотите.

 3. Drum - в конце убрать пустые строки

**Comment by coolrich** [comment]
Ок, посмотрю

**Comment by coolrich** [comment]
Есть
