### ISSUE TITLE
Таблица преобразований

### ISSUE THREAD

**Issue by milkina** [coolrich/Lessons#2]
1. Где принимающий тип?  Сбоку или сверху?
2. Тип char совместим со всеми числовыми типами.

**Comment by milkina** [comment]
Из short в int ,long, float,double -не явный. В программе же правильно сделали.
Из int в byte,short,char - явный. А во все остальные типы  -не явный.

Просмотрите еще раз табличку.

**Comment by coolrich** [comment]
Сделал
