### ISSUE TITLE
WordFinder.findSmallest

### ISSUE THREAD

**Issue by milkina** [coolrich/Lessons#22]
1. 
     while (matcher.find()) {
            strings.add(new StringBuilder());
            for (int i = 0; i < matcher.group().length(); i++) {
                strings.get(count).append(matcher.group().charAt(i));
            }
            count++;
        }
Почему нельзя сделать просто 
        while (matcher.find()) {
            strings.add(new StringBuilder(matcher.group()));
        }
?
2.  Должно находиться слово с минимальным количеством разных букв. То есть из строки
ff afasdfs ffffffffffffffffff s aaaaa b, должно найтись слово 'ff'.

**Comment by coolrich** [comment]
У меня сделано так что выводятся все слова с одинаковым минимальным количеством символов

**Comment by coolrich** [comment]
Например, если есть два слова ff то на экран выводятся оба

**Comment by milkina** [comment]
То что выводите несколько слов, это хорошо.
Но из строки "afasdfs ffffffffffffffffff s aaaaa b"  у вас выводится только b, s.
А должно быть "ffffffffffffffffff s aaaaa b"  .
Может что-то не долили?

**Comment by coolrich** [comment]
Ок, буду корректировать.

**Comment by coolrich** [comment]
Есть
