### ISSUE TITLE
Обобщённые типы. Задание про обобщение класса Matrix

### ISSUE THREAD

**Issue by coolrich** [coolrich/Lessons#23]
Часто ли при работе с обобщенными типами пользуются операторами instanceof, а также методами intVal(),floatVal() и.т.п или они здесь излишни ? В задании про матрицу, я создал кучу всяких методов для приведения к фактическому типу и выполнения для него соответствующих операций, после чего мне показалось что я не совсем верно понимаю обобщённые типы, по этому хотелось бы узнать что в этом задании не так.

**Comment by milkina** [comment]
У всех классов-оберток есть метод doubleValue, просто используйте его всегда.

**Comment by coolrich** [comment]
Нужно переделать задание  с использованием только doubleValue(), или так как сейчас тоже правильно?

**Comment by milkina** [comment]
Ну, лучше переделайте - код будет чище.

**Comment by coolrich** [comment]
Готово. Жду проверки
