### ISSUE TITLE
Matrix

### ISSUE THREAD

**Issue by milkina** [coolrich/Lessons#24]
1. getNumber - можно всегда вызывать метод doubleValue.
2. addMatrix - можно просто
    Number n = twoDimMatrix[i][j].doubleValue() + anotherMatrix.getElement(i, j).doubleValue();
Тоже самое и в др. методах.
3. Вместо 
  Matrix<Float> m = new Matrix(new Float[][]{{1f, 1f}, {1f, 1f}});
лучше 
  Matrix<Float> m = new Matrix<>(new Float[][]{{1f, 1f}, {1f, 1f}});

**Comment by coolrich** [comment]
Сделал
