### ISSUE TITLE
UnionTest

### ISSUE THREAD

**Issue by milkina** [coolrich/Lessons#25]
Немного подчистила:

public class UnionTest {
    public static <T> void union(Set<? extends T>... set) {
        Set<T> union = new HashSet<>();
        for (Set<? extends T> t : set) {
            union.addAll(t);
        }
        System.out.print("Union of sets: ");
        for (T t : union) {
            System.out.print(t + " ");
        }
    }

    public static <T> void intersect(Set<?>... set) {
        Set<T> intersect = new HashSet<>((Collection<T>) set[0]);

        for (Set<?> t : set) {
            intersect.retainAll(t);
        }
        System.out.print("intersect of sets: ");
        for (Object t : intersect) {
            System.out.print(" " + t);
        }
    }

    public static void main(String[] args) {
        union(new HashSet<>(Arrays.asList("a", "b", "c", "d")), new HashSet<>(Arrays.asList("c", "d", "e", "f")));
        System.out.println();
        intersect(new HashSet<>(Arrays.asList("a", "b", "c", "d")), new HashSet<>(Arrays.asList("c", "d", "e", "f")), new HashSet<>(Arrays.asList("e", "f", "c", "d", "g", "h")));
    }
}

**Comment by coolrich** [comment]
Сделал
