### ISSUE TITLE
Дробная часть

### ISSUE THREAD

**Issue by coolrich** [coolrich/Lessons#26]
Как сделать так, что бы в переменной типа дробного числа после запятой ноль тоже учитывался в длину  строки?
Я вот нашёл вариант с BigDecimal.scale(), но может есть ещё варианты?

**Comment by milkina** [comment]
Не совсем поняла вопрос - это при формитировании, парсинге? В каком контексте?

**Comment by coolrich** [comment]
При формировании

**Comment by milkina** [comment]
Например так подойдет?
  NumberFormat numberFormat = NumberFormat.getInstance();
        numberFormat.setMinimumFractionDigits(1);
        String s = numberFormat.format(3.0);
        System.out.println(s.length());

**Comment by coolrich** [comment]
Ок
