### ISSUE TITLE
Область видимости

### ISSUE THREAD

**Issue by coolrich** [coolrich/Lessons#27]
В чём может быть причина, когда два класса(пускай 1-й и 2-й) в одном пакете и я пытаюсь добавить экземпляр 1-го в коллекцию, которая является полем 2-го, то пишет что "Cannot access..." ?
1-й

`package lesson20.atHome.e5;`
`public class Fork{`
  `  private static int forkId=0;`
    `private final int id=++forkId;`
  `  public Fork() {`
   ` }`
  `  public static int getForkId() {`
       ` return forkId;`
`    }`
 `   public int getId() {`
       ` return id;`
   ` }`
`}`

2-й 

`package lesson20.atHome.e5;`
`import java.util.ArrayList;`
`import java.util.List;`
`public class Table {`
   ` private List<Fork> forkList;`
  `  public Table() {`
       ` forkList = new ArrayList<>();`
       ` forkList.add(new Fork());//Cannot access  lesson20.atHome.e5.Fork`
       ` forkList.add(new Fork());//Cannot access  lesson20.atHome.e5.Fork`
       ` forkList.add(new Fork());//Cannot access  lesson20.atHome.e5.Fork`
       ` forkList.add(new Fork());//Cannot access  lesson20.atHome.e5.Fork`
       ` forkList.add(new Fork());//Cannot access  lesson20.atHome.e5.Fork`
    }
}
`

**Comment by coolrich** [comment]
А вот если по разным пакетам расфасовать, то эта ошибка исчезает

**Comment by coolrich** [comment]
А может это баг в идее?

**Comment by milkina** [comment]
У меня сейчас работает. В таких случаях можно попробовать сделать Rebuild Project.

**Comment by coolrich** [comment]
Спасибо, буду знать
