### ISSUE TITLE
lesson3. Summ

### ISSUE THREAD

**Issue by milkina** [coolrich/Lessons#3]
1. Убрать ненужные пустые строки
2. Вынести в отдельный метод, который будет вызываться два раза
  if (sc.hasNextInt()) {
                a = sc.nextInt();
                 System.out.println(query2);
   } else {
          isWrong = true;
    }

**Comment by milkina** [comment]
1.  Пусть метод принимает на вход только объект класса Scanner и возвращает одно введенное пользователем число:
 private static int checkInput(Scanner sc)
Этот метод вызывается два раза для каждого числа.

**Comment by coolrich** [comment]
Какие есть варианты очистки буфера потока ввода/вывода помимо использования метода next() класса Scanner?

**Comment by milkina** [comment]
Никаких. 
Во всяком случае я их не знаю.

**Comment by coolrich** [comment]
В общем сделал, жду вашей проверки

**Comment by milkina** [comment]
Done, но неотформатировано.

**Comment by coolrich** [comment]
Сделал
