### ISSUE TITLE
PrematureDownBubbleSorter1

### ISSUE THREAD

**Issue by milkina** [coolrich/Lessons#6]
1.  Неотформатировано
2. Вместо  if(b==true) лучше if(b)
3.  Метка Inner не нужна. При break у вас и так закончится внутренний цикл.

**Comment by coolrich** [comment]
Сделал

**Comment by milkina** [comment]
И еще пропустила:
1. Убрать неннжный комментарий
2. Убрать ненужные переводы строки

**Comment by coolrich** [comment]
Done

**Comment by milkina** [comment]
Done
Документирующий комментарий можно оставлять ( и нужно). Ненужный комментарий - это однострочный и многострочный, там где вы, например, закомментировали неиспользуемый код.
